### ISSUE TITLE
Can you make a tutorial?

### ISSUE THREAD

**Issue by unknownUserHereAndThere** [ipriyam26/Movies#1]

**Comment by ipriyam26** [comment]
Okay will do that give me sometime, till then you can tell me what issues you are facing

**Comment by mangeshghodke** [comment]
after selecting stream webtorrent exits.

**Comment by mangeshghodke** [comment]
> after selecting stream webtorrent exits.

hey solved it, mpv was not opening, so changed to vlc in code and it worked. thanks for this project.

**Comment by ipriyam26** [comment]
Welcome, share with friends and family 🙂👌
