### ISSUE TITLE
ModuleNotFoundError: No module named 'termios'

### ISSUE THREAD

**Issue by Tonda39** [ipriyam26/Movies#2]
I have followed instructions but when I try to run "python main.py" I get this error message
![Screenshot 2022-02-22 215615](https://user-images.githubusercontent.com/84375208/155218229-02aa0943-2d29-4c4e-95c0-5e554a1bd9d0.png)
.

**Comment by darrenmcewan** [comment]
Termios is not available on Windows per [termios python docs](https://docs.python.org/3/library/termios.html#module-termios)

**Comment by ipriyam26** [comment]
will be switching to something cross platform on the next update please wait for a while

**Comment by ipriyam26** [comment]
> I have followed instructions but when I try to run "python main.py" I get this error message ![Screenshot 2022-02-22 215615](https://user-images.githubusercontent.com/84375208/155218229-02aa0943-2d29-4c4e-95c0-5e554a1bd9d0.png) .

I have made a few changes please clone the latest version and check if it is working or not

**Comment by Tonda39** [comment]
I've cloned the newest version and followed new instructions but now after I run "python3 main.py" it just says: "Redirection is not supported."

**Comment by Tonda39** [comment]
Ok, it's working now. I just had to run it in through CMD and not GIT Bash.

**Comment by ipriyam26** [comment]
> Ok, it's working now. I just had to run it in through CMD and not GIT Bash.

Great 👌 share with your friends if you like it
