### ISSUE TITLE
Does this work on Windows?

### ISSUE THREAD

**Issue by dbkalaria** [ipriyam26/Movies#5]
Hello, just came to know about this from Reddit and I found this amazing. But I tried it on windows but facing this issue.
`Redirection is not supported.`

**Comment by dbkalaria** [comment]
Hello, just came to know about this from Reddit and I found this amazing. But I tried it on windows but facing this issue.
`Redirection is not supported.`

**Comment by ipriyam26** [comment]
can you guide me at what stage did you get this error, where you able to install all the dependencies?

**Comment by dbkalaria** [comment]
I started the installation by running `setup.py` and then I installed the dependencies i.e. MPV and web-torrent-cli. 

After that when I run `main.py` I get the above error.

**Comment by ipriyam26** [comment]
pip install windows-curses
install this

**Comment by dbkalaria** [comment]
Sorry, my bad, I had used git bash to clone the repo and forgot to switch to the command prompt and run the script directly in the bash terminal and bash was restricting the redirection. Sorry and thanks for the quick replies.

**Comment by ipriyam26** [comment]
No issue share the project with your friends and family if you liked it ☺️

**Comment by dbkalaria** [comment]
Yes sure will share it. And also try to do some contributions related to GUI if possible.

**Comment by ipriyam26** [comment]
GUI will consume more resources then needed still i will see if it's a popular demand

**Comment by dbkalaria** [comment]
Okay, I was talking about I will try to do a contribution. :)
